name: learn-github -actions
on: [push]
jobs:
  check-in:
    runs-on: ubuntu-latest
  
    steps:
    - name: Hello! 💬
      run: cat(paste0("Hello ", Sys.getenv("NAME"), "! 👋"))
      shell: Rscript {0} 
      env:
        NAME: "Viola"
        
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'

