name: learn-github -actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up T
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'
